fix curl upload

diff --git a/generate_conversion-cli b/generate_conversion-cli
--- a/generate_conversion-cli
+++ b/generate_conversion-cli
@@ -7,33 +7,50 @@ main(){
   file="${2:-}"
 
   if [ -z "$working_dir" ];then
-    echo "the is no directory provided" 
+    echo "the is no directory provided"
     exit 1
   fi
 
   if [ ! -d "$working_dir" ];then
-    echo "this ${working_dir} directory does not exist" 
+    echo "this ${working_dir} directory does not exist"
     exit 1
   fi
 
   if [ -z "$file" ];then
-    echo "the is no file provided" 
+    echo "the is no file provided"
     exit 1
   fi
 
   if [ ! -e "$file" ];then
-    echo "this ${file} file does not exist" 
+    echo "this ${file} file does not exist"
     exit 1
   fi
 
   case "$file" in
-      *.pdf) 
+      *.pdf)
           full_name="${file##*/}"
-          url="$(curl "https://bashupload.com/$full_name" --data-binary "@$file" | grep -o "https://bashupload.com/.*/${full_name}")"
-          if [ $? -ne 0 ];then
-            echo "curl status is not 0"
+
+          # echo curl "https://bashupload.com/$full_name" --data-binary "@$file"
+          # url="$(curl "https://bashupload.com/$full_name" --data-binary "@$file" | grep -o "https://bashupload.com/.*/${full_name}")"
+
+          encoded_full_name=$(echo "$full_name" | sed 's/ /%20/g')
+          encoded_file=$(echo "$file" | sed 's/ /%20/g')
+          if ! url="$(curl -s "https://bashupload.com/${encoded_full_name}" --data-binary "@${file}")";then
+            echo "curl error msg:"
+            echo "$url"
             exit 1
           fi
+
+          echo "curl result:"
+          echo "$url"
+          if ! url="$(echo "$url" | grep -o "https://bashupload.com/.*pdf")";then
+            echo "grep error msg:"
+            echo "$url"
+            exit 1
+          fi
+
+          # echo "fin"
+          # exit 0
 
           if [ -z "$url" ];then
             echo "the url is empty, curl is failed"
@@ -120,10 +137,10 @@ main(){
 
   task=$(printf "%s" "${selected_tasks[@]}")
   # echo "$task"
-  
+
   # exit 1
   clear
-  
+
   cmd=''
   cmd+='#!/bin/bash\n\n'
   cmd+='set -x\n\n'
@@ -151,7 +168,7 @@ main(){
   cmd+='    exit 1\n'
   cmd+='fi\n\n'
   cmd+="echo '- [${name}](${summary_output})' >> ./src/SUMMARY.md"
-  
+
   cd "$working_dir" || exit
   echo -e "$cmd" > ./convert.sh
 
