(generate_conversion-cli) improve

diff --git a/generate_conversion-cli b/generate_conversion-cli
--- a/generate_conversion-cli
+++ b/generate_conversion-cli
@@ -1,4 +1,5 @@
 #!/bin/bash
+# shellcheck disable=2016
 
 clear
 cmd=""
@@ -16,25 +17,25 @@ remove_task() {
   tasks=("${tasks[@]}")  # Remove empty placeholders
 }
 
-#1langs=('English (en)' 'French (fr)')
-#1select lang_option in "${langs[@]}"; do
-#1  case $lang_option in
-#1    'English (en)')
-#1      lang='en'
-#1      break
-#1      ;;
-#1    'French (fr)')
-#1      lang='fr'
-#1      break
-#1      ;;
-#1    *)
-#1      echo 'Invalid option'
-#1      exit 1
-#1      ;;
-#1  esac
-#1done
-#1
-#1clear
+langs=('English (en)' 'French (fr)')
+select lang_option in "${langs[@]}"; do
+  case $lang_option in
+    'English (en)')
+      lang='en'
+      break
+      ;;
+    'French (fr)')
+      lang='fr'
+      break
+      ;;
+    *)
+      echo 'Invalid option'
+      exit 1
+      ;;
+  esac
+done
+
+clear
 
 tasks=('Ocr to correcte text' 'Paraphrase text for beginner' 'Ocr then paraphrase' 'pass')
 selected_tasks=()
@@ -81,28 +82,28 @@ while $need_more_task;do
   done
 done
 
-# echo "$task"
 task=$(printf "%s" "${selected_tasks[@]}")
 echo "$task"
 
-exit 1
+# exit 1
 clear
 
 file="${1:-/tmp/1.pdf}"
 output="file.md"
 
-cmd=""
-cmd+="CONVERSION=false\n"
-cmd+="\n"
-cmd+="if python3 llmtask.py "
+cmd=''
+cmd+='CONVERSION=true\n'
+cmd+='\n'
+cmd+='if ! python3 llmtask.py '
 cmd+="--lang $lang "
-cmd+="--ocr /usr/bin/tesseract "
+cmd+='--ocr /usr/bin/tesseract '
 cmd+="$task "
 cmd+="--file $file "
 cmd+="1>$output"
-cmd+="; then\n"
-cmd+="    CONVERSION=false\n"
-cmd+="    echo \"some errors\"\n"
-cmd+="fi"
+cmd+='; then\n'
+cmd+='    CONVERSION=false\n'
+cmd+='    echo "some errors"\n'
+cmd+='fi\n\n'
+cmd+='echo "CONVERSION=$CONVERSION" >> $GITHUB_ENV'
 
 echo -e "$cmd"
