(generate_conversion-cli) fix + improve

diff --git a/generate_conversion-cli b/generate_conversion-cli
--- a/generate_conversion-cli
+++ b/generate_conversion-cli
@@ -16,48 +16,58 @@ remove_task() {
   tasks=("${tasks[@]}")  # Remove empty placeholders
 }
 
-langs=('English (en)' 'French (fr)')
-select lang_option in "${langs[@]}"; do
-  case $lang_option in
-    'English (en)')
-      lang='en'
-      break
-      ;;
-    'French (fr)')
-      lang='fr'
-      break
-      ;;
-    *)
-      echo 'Invalid option'
-      exit 1
-      ;;
-  esac
-done
+#1langs=('English (en)' 'French (fr)')
+#1select lang_option in "${langs[@]}"; do
+#1  case $lang_option in
+#1    'English (en)')
+#1      lang='en'
+#1      break
+#1      ;;
+#1    'French (fr)')
+#1      lang='fr'
+#1      break
+#1      ;;
+#1    *)
+#1      echo 'Invalid option'
+#1      exit 1
+#1      ;;
+#1  esac
+#1done
+#1
+#1clear
 
-clear
-
-tasks=('Ocr to correcte text' 'Paraphrase text for beginner' 'pass')
-
+tasks=('Ocr to correcte text' 'Paraphrase text for beginner' 'Ocr then paraphrase' 'pass')
+selected_tasks=()
+# set -x
+task=""
 need_more_task=true
 while $need_more_task;do
+  clear
   if [ ${#tasks[@]} -le 1  ];then
     break
   fi
   select task_option in "${tasks[@]}" ; do
     case $task_option in
       'Ocr to correcte text')
-        task+='--llm correct_ocr '
+        selected_tasks+=('--llm correct_ocr ')
         remove_task "$task_option"
         break
         ;;
       'Paraphrase text for beginner')
-        task+='--llm correct_ocr '
+        selected_tasks+=('--llm paraphrasing ')
+        remove_task "$task_option"
+        break
+        ;;
+      'Ocr then paraphrase')
+        selected_tasks+=('--llm correct_ocr --llm paraphrasing ')
+        remove_task 'Ocr to correcte text'
+        remove_task 'Paraphrase text for beginner'
         remove_task "$task_option"
         break
         ;;
       'pass')
         need_more_task=false
-        if [ -z "$task" ];then
+        if [ ${#tasks[@]} -lt 1  ];then
           echo "We should provide at least one task"
           exit 1
         fi
@@ -71,9 +81,12 @@ while $need_more_task;do
   done
 done
 
-# exit 1
+# echo "$task"
+task=$(printf "%s" "${selected_tasks[@]}")
+echo "$task"
+
+exit 1
 clear
-# exit 1
 
 file="${1:-/tmp/1.pdf}"
 output="file.md"
