(pdf2md.yml) try to continue if python llmtask failed to remove pdfs

diff --git a/.github/workflows/pdf2md.yml b/.github/workflows/pdf2md.yml
--- a/.github/workflows/pdf2md.yml
+++ b/.github/workflows/pdf2md.yml
@@ -73,8 +73,15 @@ jobs:
             tasks+=("$line")
           done < tasks.txt
           echo "${tasks[*]}"
-          echo eval "python3 llmtask.py ${tasks[*]} --lang $LANG --ocr /usr/bin/tesseract --file $FILE 1>$OUTPUT; rm -f $FILE && cat /dev/null > ./tasks.txt"
-          eval "python3 llmtask.py ${tasks[*]} --lang $LANG --ocr /usr/bin/tesseract --file $FILE 1>$OUTPUT; rm -f $FILE && cat /dev/null > ./tasks.txt"
+
+          echo eval "python3 llmtask.py ${tasks[*]} --lang $LANG --ocr /usr/bin/tesseract --file $FILE 1>$OUTPUT || echo some errors"
+          eval "python3 llmtask.py ${tasks[*]} --lang $LANG --ocr /usr/bin/tesseract --file $FILE 1>$OUTPUT || echo some errors"
+
+          echo "rm -f $FILE"
+          rm -f "$FILE"
+
+          echo "cat /dev/null > ./tasks.txt"
+          cat /dev/null > ./tasks.txt
 
       - name: Commit and push changes
         env:
